on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: checks

jobs:
  linter-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Run linters
        run: make lint

  vet-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - uses: actions/checkout@v3

      - name: Run go vet
        run: |
          go vet ./...
